# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD

  identity:
    image: identity
    build:
      context: ./src/identity
    ports:
      - 5000:80

  user:
    image: user
    build:
      context: ./src/user
    ports:
      - 5010:80

  messages:
    image: messages
    build:
      context: ./src/messages
    ports:
      - 5020:80

  gateway:
    image: gateway
    build:
      context: ./src/gateway
      args:
        - NODE_ENV=development
    ports:
      - 4000
