version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/
      - ./src/UserService/Data/Migrations/init_db.sql:/docker-entrypoint-initdb.d/init_user_service_db.sql

  user_service:
    image: dotnet-federation/user
    build:
      context: ./src/UserService
    depends_on:
      - db
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DOTNET_ConnectionStrings__DefaultConnection=Host=db:5432;Database=user_service;Username=postgres;Password=${POSTGRES_PASSWORD}'

  gateway:
    image: dotnet-federation/gateway
    build:
      context: ./src/gateway
      args:
        - NODE_ENV=development
    depends_on:
      - user
    ports:
      - 4000:4000

volumes:
  db:
