version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/

  user:
    image: dotnet-federation/user
    build:
      context: ./src/user
    depends_on:
      - db
    ports:
      - 5000:80
    environment:
      - 'DOTNET_ConnectionStrings__DefaultConnection=Host=db:5432;Database=user;Username=postgres;Password=password'

  gateway:
    image: dotnet-federation/gateway
    build:
      context: ./src/gateway
      args:
        - NODE_ENV=development
    depends_on:
      - user
    ports:
      - 4000:4000

volumes:
  db:
