version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql
      - ./Identity.Data/Migrations/init_db.sql:/docker-entrypoint-initdb.d/init_identity_db.sql

  identity_infrastructure:
    image: dotnet-federation/identity/infrastructure
    build:
      context: ./Identity.Data
    depends_on:
      - db
    volumes:
      - ../../../scripts/wait-for.sh:/wait-for.sh
    entrypoint:
      - sh
      - -c
      - '/wait-for.sh db:5432 -- dotnet ef database update'
    environment:
      - 'DOTNET_ConnectionStrings__IdentityConnection=Host=db;Database=identity;Username=postgres;Password=${POSTGRES_PASSWORD}'

  identity_api:
    image: dotnet-federation/identity/api
    build:
      context: .
      dockerfile: ./Identity.API/Dockerfile
    depends_on:
      - db
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DOTNET_ConnectionStrings__IdentityConnection=Host=db;Database=identity;Username=postgres;Password=${POSTGRES_PASSWORD}'

volumes:
  db: {}
